bot:
  automerge: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux:
    - github_actions
conda_build:
  pkg_format: 2
upload_on_branch: main
github_actions:
  self_hosted: true
  self_hosted_triggers: ["pull_request"]
  self_hosted_labels:
    - cirun-openstack-gpu
