bot:
  automerge: true
  automerge_options:
    ignored_statuses:
    - linter
conda_forge_output_validation: true
provider:
  linux: azure
  linux_aarch64: default
  osx: azure
  win: azure
github:
  branch_name: main
  tooling_branch_name: main
